version: '3.8'

services:
  frontend:
    container_name: LoL-S-Tracker
    image: docker-nextjs-dev-lol-s-tracker
    build:
      context: .
      dockerfile: dockerfile
    restart: unless-stopped
    ports:
      - 3000:3000
